trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  webAppName: 'CVGenerator-Agilos'
  nodeVersion: '20.x'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: Install Node.js

    - script: npm install --production
      displayName: npm install

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
        excludePatterns: |
          .git/**
          .github/**
          temp/**
          test/**
          docs/**
          *.pdf
          **/*.docx
      displayName: Package app

    - publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: drop

- stage: Deploy
  displayName: Deploy to Azure
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'AgilosLab-ServiceConnection'
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: 'NODE|20-lts'
            displayName: Deploy to Azure Web App
